"""empty message

Revision ID: a50ae9654dbc
Revises: 9493b7a19da9
Create Date: 2025-03-07 19:45:32.416123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50ae9654dbc'
down_revision = '9493b7a19da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('starship_class', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=120), nullable=True),
    sa.Column('crew', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.String(length=120), nullable=True),
    sa.Column('consumables', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starship_favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starship_favourite_user_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starship_favourite_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('starship_favourite_user_id'),
    sa.UniqueConstraint('starship_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starship_favourites')
    op.drop_table('starships')
    # ### end Alembic commands ###
